### ISSUE TITLE
Assassin's Creed : Revelations hangs during savegame loading

### ISSUE THREAD

**Issue by Odelpasso** [Joshua-Ashton/d9vk#154]
The game runs and you can to navigate in the main menu without issue when D9VK is enabled. But each time you try to load a savegame to continue a party, the game hang and you need to kill the game's process.

When you replay apitrace with wined3d/Nine, you can see the loading stage of the savegame. Oddly, you can pass the loading stage when you replay apitrace with D9VK.

If i disable DXVK State Cache, the game hangs randomly.

### Software information
Name of the game, settings used etc.

### System information
- GPU: AMD R580 8Gb
- Driver: Mesa-git + LLVM 9
- Wine version: Wine-Staging-4.9
- D9VK version: last D9VK-git

### Apitrace file(s)
- https://drive.google.com/open?id=1O817MlLidTwVwZgrZenpLDTXWqy97F36

### Log files
- d3d9.log: [ACRSP_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3268636/ACRSP_d3d9.log)

### Other small bug  
You can see that there is an small issue between D9VK and Nine/Wined3d when you're at this step before to push a button to go to the main menu.

D9VK screen :
![Capture du 2019-06-08 18-07-51](https://user-images.githubusercontent.com/3606036/59148476-ba830c00-8a09-11e9-9b68-d8859aa4914a.png)

Nine/Wined3d screen : 
![Capture du 2019-06-08 18-21-06](https://user-images.githubusercontent.com/3606036/59148479-c7076480-8a09-11e9-9509-10b5f86d9d07.png)

**Comment by K0bin** [comment]
The logs mention the format `1112945234` which is AL16.
I think in WineD3D, it's a 32 Bit Format where the last 16 Bit are alpha and the first 16 Bit are empty.

**Comment by Odelpasso** [comment]
I tried your branch K0bin and the game still crashes during loading savegame.
[ACRSP_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3268718/ACRSP_d3d9.log)

I still have `warn:  ConvertFormat: Unknown format encountered: Invalid Format (1112945234)` in this d3d9.log

**Comment by Joshua-Ashton** [comment]
I've implemented ColorFill here

fb03246abe449f408bb085350dbecae19ea03fe3

I will test this for your usecase tomorrow.

**Comment by Odelpasso** [comment]
The game still crash with vanilla D9VK and D9VK+ R16 + AL16 patches from Rhedox
It still crashes at the same point, during the loading scene :
![Capture du 2019-06-13 06-57-59](https://user-images.githubusercontent.com/3606036/59404940-e525e980-8da8-11e9-9b82-2ae7a5d995ab.png)

- d3d9.log : [ACRSP_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3284275/ACRSP_d3d9.log)

**Comment by Odelpasso** [comment]
I think i can close this bug report since it fixed on Master.

**Comment by K0bin** [comment]
For reference: fixed by 08755c2
