### ISSUE TITLE
A Hat in Time: Crashing when opening save and/or entering level

### ISSUE THREAD

**Issue by 808-cowbell** [Joshua-Ashton/d9vk#216]
Title says all. I am occasionally able to enter the spaceship, but bigger levels as far as I can tell crash without fail. I believe this is a memory allocation issue.

### Software information
A Hat in Time, crashes on all settings

### System information
- GPU: Nvidia GTX 1070ti 8GB
- Driver: 418.56.0
- Proton version: 4.2-9
- D9VK version: 0.13, 0.12

### Log files
- [HatinTimeGame_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3387967/HatinTimeGame_d3d9.log)

**Comment by K0bin** [comment]
This is because of a Nvidia driver issue that we havent been able to figure out yet. 
If it does happen consistently for you, please help debugging this: https://github.com/doitsujin/dxvk/issues/1100#issuecomment-509484527

**Comment by ryao** [comment]
@808-cowbell Is this still an issue? I cannot reproduce it on Proton 4.11-3 with `PROTON_USE_D9VK=1 %command%` in my launch options.

**Comment by 808-cowbell** [comment]
@ryao Just re-installed the game, I'll be in class this afternoon so I'll get back to you then. Some variables have changed though, I'm now on Manjaro KDE with Nvidia 430.5 drivers.

**Comment by 808-cowbell** [comment]
@ryao Yes, can still reproduce. This time I am also using version 0.20 of D9VK.

**Comment by ahuillet** [comment]
Can you please reproduce the problem then attach nvidia-bug-report.sh output?

**Comment by ryao** [comment]
@808-cowbell It might also help if you attach your save file. It should be located in `~/.steam/steam/steamapps/common/HatinTime/HatinTimeGame/SaveData/slot1.hat`, provided that you are using the first save slot.

**Comment by 808-cowbell** [comment]
@ahuillet Please show me how I can do this. I've seen [#1100 (comment)](https://github.com/doitsujin/dxvk/issues/1100#issuecomment-509484527) but I'm not sure how to get to bash before module load time in Manjaro, or how to disable debugging after I've gotten a reproduction.

**Comment by ahuillet** [comment]
Ignore that comment, just reproduce the problem then run nvidia-bug-report.sh as root.
And please provide detailed instructions for how to reproduce the problem so we can attempt to replicate your results.

**Comment by 808-cowbell** [comment]
Alright, gotcha. Here is the log file and my slot 1 save.
1. Logged into Manjaro, nothing is running at this point
2. Started A Hat in Time with D9VK 0.20
3. Loaded into spaceship, went to Act 1 of the Arctic Cruise chapter.
4. When loading, the game notifies me that I have ran out of video memory and exits.

[nvidia-bug-report.log.gz](https://github.com/Joshua-Ashton/d9vk/files/3579559/nvidia-bug-report.log.gz)
[slot1.tar.gz](https://github.com/Joshua-Ashton/d9vk/files/3579578/slot1.tar.gz)

**Comment by ryao** [comment]
@808-cowbell It looks like your system might be running out of memory. At the loading screen, the system is using >6GB (the figure is in kilobytes) of RAM for me:
```
ps -p $(pgrep HatinTimeGame.e) -o '%z'
   VSZ
6469320
```
Going into the spaceship uses another gigabyte:
```
$ ps -p $(pgrep HatinTimeGame.e) -o '%z'
   VSZ
7411020
```
Loading a world (I choose 2-5) increases it further (although not by much):
```
$ ps -p $(pgrep HatinTimeGame.e) -o '%z'
   VSZ
7487352
```
I missed the opportunity to get Arctic Cruise as an existing user, so I cannot test it, but my guess is that Arctic Cruise sends memory usage even higher. Your steam log is from actually being out of system memory.

Proton/d9vk in that they might not be using memory as efficiently as Windows, but that would need to be checked.

**Comment by ryao** [comment]
@808-cowbell Wou could try using wined3d. It is much kinder on memory usage because it doesn't preallocate memory. At the same time, its performance isn't as good. There is also a bug in wined3d in chapter 1's rain scenes.

**Comment by ryao** [comment]
@808-cowbell Here is another option. Try doing `sysctl vm.overcommit=1` as root and see if the game works.

**Comment by 808-cowbell** [comment]
> I missed the opportunity to get Arctic Cruise as an existing user, so I cannot test it, but my guess is that Arctic Cruise sends memory usage even higher. Your steam log is from actually being out of system memory.

If I'm reading this right, does this mean that if I were to upgrade my memory, I would be able to perhaps load the level? It's very odd that A Hat in Time alone would use that much memory.

> @808-cowbell Here is another option. Try doing `sysctl vm.overcommit=1` as root and see if the game works.

`sysctl: cannot stat /proc/sys/vm/overcommit: No such file or directory`

**Comment by ryao** [comment]
@808-cowbell You are correct. More system memory would make this issue disappear. It is odd that A Hat in Time uses so much memory, but it development team only has 1 programmer. My guess is that reducing memory usage isn’t high on his list on priorities. I am told that memory usage is roughly 1GB lower on Windows, which is probably why people there aren’t encountering this this. There might be room for D9VK to improve here.

**Comment by ryao** [comment]
@808-cowbell I posted a more detailed explanation of why testing `sysctl vm.overcommit_memory=1` could be useful here:

https://github.com/doitsujin/dxvk/issues/1100#issuecomment-528615085

That said, I am on the fence as to whether this would be helpful in your situation.

**Comment by 808-cowbell** [comment]
Was able to load into the Arctic Cruise, your hypothesis is correct. I closed the game shortly after the level loaded.
[nvidia-bug-report.log.gz](https://github.com/Joshua-Ashton/d9vk/files/3581760/nvidia-bug-report.log.gz)

**Comment by 808-cowbell** [comment]
@ryao Is there anything wrong with adding `sysctl vm.overcommit_memory=1` to startup options, or would it be safer to only use this when playing a problematic game? I would close this, but I haven't been able to do any extensive testing of the game yet.

**Comment by ryao** [comment]
@SveSop You could add `vm.overcommit_memory=1` to `/etc/sysctl.conf` and it should be set at startup. This might have side effects, but offhand, I do not see them making a difference on a desktop system.

Anyway, this is related to an issue that engineers from nvidia have been trying to solve for months, so I expect nvidia to do something here to avoid the need to set that. It might involve making vulkan allocations hook into `MAP_NORESERVE` like nearly all other userland memory allocations do, but that is speculation on my part.

**Comment by wgpierce** [comment]
@808-cowbell in my testing with 8GB sysmem (regardless of vm.overcommit_memory), I could sometimes load Arctic Cruise once with no problems, but I could never quit to menu and load it again successfully. Can you try this out and see if you can load it twice with any configuration?

**Comment by 808-cowbell** [comment]
I actually haven't been able to load the Arctic Cruise again at all, even with overcommits. Here is another log.
[nvidia-bug-report.log.gz](https://github.com/Joshua-Ashton/d9vk/files/3584201/nvidia-bug-report.log.gz)

**Comment by ryao** [comment]
@808-cowbell A proton log would be helpful here, but I am willing to assume that it would be the same as the original.

It would be a horrible hack, but we could try looping in the allocation function on Nvidia hardware until a timeout is reached. We could print warnings whenever we need to loop when these allocations fail. This is another stab in the dark. I do not have spare cycles to dedicate to this today, but I likely could do something on Monday and provide binaries for people to test.

**Comment by 808-cowbell** [comment]
I mean, I think it's high time for me to upgrade my memory anyways. Should 16GB be enough headroom?

**Comment by ryao** [comment]
> I mean, I think it's high time for me to upgrade my memory anyways. Should 16GB be enough headroom?

I have not heard of any games needing more than that. If any do, only 5.28% of systems would be able to run them:

https://store.steampowered.com/hwsurvey

**Comment by Joshua-Ashton** [comment]
I believe this should be solved with newer NV drivers, can people confirm this?

**Comment by 808-cowbell** [comment]
> I believe this should be solved with newer NV drivers, can people confirm this?

I can certainly test this soon, I'm running 440xx at the moment. I'll keep you posted!

**Comment by 808-cowbell** [comment]
I can still get a reproduction on this, here is the Nvidia bug report.
[nvidia-bug-report.log.gz](https://github.com/Joshua-Ashton/d9vk/files/3898568/nvidia-bug-report.log.gz)

**Comment by wgpierce** [comment]
The change didn't make it to 440 yet, but it is in the Vulkan beta driver. Can you try out that one?
It's under "Linux 435.27.08" here: https://developer.nvidia.com/vulkan-driver . Or if you get it from your package manager, make sure the version matches that one.

**Comment by 808-cowbell** [comment]
Testing on 440.59, which I believe is the first stable driver to incorporate the change. No longer able to reproduce the problem, the game loads the Arctic Cruise every time.
