### ISSUE TITLE
World of Warcraft 1.12 ground texture issue

### ISSUE THREAD

**Issue by STiAT** [Joshua-Ashton/d9vk#219]
After the black-screen issue was fixed for the WoW 1.12 client we get a bit further, and can see the ground textures seem to be missing in some areas (not all, some ground textures are there, for me it looked like flat surfaces are properly displayed, terrain not), see screenshot:
![Screenshot from 2019-07-13 13-20-35](https://user-images.githubusercontent.com/1781015/61171056-7340eb80-a572-11e9-9af7-4146dc5f8991.png)

I've taken an apitrace (d3d9.dll from apitrace), I hope I did that one right (was the first trace I did). The performance shows it while doing the API trace, it's a lot better running without tracing ofc ;-).

### Software information
World of Warcraft 1.12 Client

### System information
- GPU: AMD Radeon RX 460 Graphics
- Driver: Mesa 19.0.6
- Wine version: wine-4.12.1
- D9VK version: 0.13 and and master (job run at 8ac70c03)

### Apitrace file(s)
https://drive.google.com/file/d/1HksLSY1Z9Y6ZxqG5uGK3kkI0egWagtes/view?usp=sharing

### Log files
d3d9.log:
```
info:  Game: WoW.exe
info:  DXVK: d9vk-0.13
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD RADV POLARIS11 (LLVM 7.0.0):
info:    Driver: 19.0.6
info:    Vulkan: 1.1.90
info:    Memory Heap[0]: 
info:      Size: 3840 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[2]: Property Flags = 0x7
info:    Memory Heap[2]: 
info:      Size: 4096 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:  AMD RADV POLARIS11 (LLVM 7.0.0):
info:    Driver: 19.0.6
info:    Vulkan: 1.1.90
info:    Memory Heap[0]: 
info:      Size: 3840 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[2]: Property Flags = 0x7
info:    Memory Heap[2]: 
info:      Size: 4096 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:  Process set as DPI aware
warn:  D3D9InterfaceEx::QueryInterface: Unknown interface query
warn:  02177241-69fc-400c-8ff1-93a44df6861d
info:  Enabled device extensions:
info:    VK_EXT_conditional_rendering
info:    VK_EXT_memory_priority
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  DXVK: Read 12 valid state cache entries
info:  DXVK: Using 9 compiler threads
warn:  D3D9: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  D3D9DeviceEx::ResetEx:
  Requested Presentation Parameters
    - Width:              1920
    - Height:             1065
    - Format:             X8R8G8B8
    - Auto Depth Stencil: true
    - Windowed:           true

warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 9
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 16
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 37
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 38
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 136
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 142
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 154
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 155
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 158
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 161
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 166
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 172
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 173
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 178
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 179
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 182
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
  Buffer size:  1920x1065
  Image count:  2
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 28
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 34
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 140
info:  D3D9DeviceEx::ResetEx:
  Requested Presentation Parameters
    - Width:              1920
    - Height:             1007
    - Format:             X8R8G8B8
    - Auto Depth Stencil: true
    - Windowed:           true

warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 143
warn:  D3D9DeviceEx::LightEnable: Stub
warn:  D3D9DeviceEx::SetLight: Stub
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_FIFO_KHR
  Buffer size:  1920x1007
  Image count:  3
info:  Game: WoW.exe
info:  DXVK: d9vk-0.13
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD RADV POLARIS11 (LLVM 7.0.0):
info:    Driver: 19.0.6
info:    Vulkan: 1.1.90
info:    Memory Heap[0]: 
info:      Size: 3840 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[2]: Property Flags = 0x7
info:    Memory Heap[2]: 
info:      Size: 4096 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:  AMD RADV POLARIS11 (LLVM 7.0.0):
info:    Driver: 19.0.6
info:    Vulkan: 1.1.90
info:    Memory Heap[0]: 
info:      Size: 3840 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[2]: Property Flags = 0x7
info:    Memory Heap[2]: 
info:      Size: 4096 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:  Process set as DPI aware
warn:  D3D9InterfaceEx::QueryInterface: Unknown interface query
warn:  02177241-69fc-400c-8ff1-93a44df6861d
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 36
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 29
```

**Comment by Joshua-Ashton** [comment]
Can you please try on a newer LLVM version and on latest master as of today. 7.0.0 is too old for D9VK to work properly.

**Comment by STiAT** [comment]
Ok, switched to llvm 8 for testing purposes, which didn't make a difference. Will not play with my main system on llvm git master, for that I'll use a different install in case I bork it.

Will try to report back later today.

**Comment by STiAT** [comment]
Okay, done that (commit was a bit earlier than "yesterday", it's 2 days ago actually).
That said, the result is the same with LLVM 9.0 (as of commit e9dc9c2bebb, current master fails building for me at the moment, didn't want to dig deeper on that yet):

### Software information

World of Warcraft 1.12 Client

### System information
    GPU: AMD Radeon RX 460 Graphics
    Driver: Mesa 19.2.0-devel (git-4e102a6de7)
    Wine version: wine-4.11
    D9VK version: 0.13 and and master (job run at 8ac70c0)
    LLVM 9.0 (git-e9dc9c2bebb)

### Screenshot
![wow-1 2-d9vk-master](https://user-images.githubusercontent.com/1781015/61186283-af07ae00-a663-11e9-8f81-fb44d71e1e47.png)

### Apitrace file(s)
https://drive.google.com/file/d/1hN1Q6J-49TPh97qiG5n8HWtoW1fkP6rw/view?usp=sharing

### Log files
```
info:  Game: WoW.exe
info:  DXVK: v1.2.3
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD RADV POLARIS11 (LLVM 9.0.0):
info:    Driver: 19.1.99
info:    Vulkan: 1.1.107
info:    Memory Heap[0]: 
info:      Size: 3840 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[2]: Property Flags = 0x7
info:    Memory Heap[2]: 
info:      Size: 4096 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:  Process set as DPI aware
warn:  D3D9InterfaceEx::QueryInterface: Unknown interface query
warn:  02177241-69fc-400c-8ff1-93a44df6861d
info:  Enabled device extensions:
info:    VK_EXT_conditional_rendering
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_host_query_reset
info:    VK_EXT_memory_priority
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  DXVK: Read 12 valid state cache entries
info:  DXVK: Using 9 compiler threads
warn:  D3D9: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  D3D9DeviceEx::ResetEx:
  Requested Presentation Parameters
    - Width:              1920
    - Height:             1065
    - Format:             X8R8G8B8
    - Auto Depth Stencil: true
    - Windowed:           true

warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 9
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 16
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 37
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 38
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 136
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 142
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 154
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 155
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 158
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 161
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 166
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 172
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 173
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 178
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 179
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 182
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
  Buffer size:  1920x1065
  Image count:  3
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 28
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 34
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 140
info:  D3D9DeviceEx::ResetEx:
  Requested Presentation Parameters
    - Width:              1920
    - Height:             1051
    - Format:             X8R8G8B8
    - Auto Depth Stencil: true
    - Windowed:           true

warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 143
warn:  D3D9DeviceEx::LightEnable: Stub
warn:  D3D9DeviceEx::SetLight: Stub
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_FIFO_KHR
  Buffer size:  1920x1051
  Image count:  4
info:  Game: WoW.exe
info:  DXVK: v1.2.3
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD RADV POLARIS11 (LLVM 9.0.0):
info:    Driver: 19.1.99
info:    Vulkan: 1.1.107
info:    Memory Heap[0]: 
info:      Size: 3840 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[2]: Property Flags = 0x7
info:    Memory Heap[2]: 
info:      Size: 4096 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:  Process set as DPI aware
warn:  D3D9InterfaceEx::QueryInterface: Unknown interface query
warn:  02177241-69fc-400c-8ff1-93a44df6861d
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 36
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 29
```

**Comment by STiAT** [comment]
### Updating
Tested with LLVM10 (git-d8bdb9225ce) mesa (git-c37df5feaa2), and d9vk 0.13f (release).
Same issue.

### APITrace
Took a new apitrace, not sure the last one got it right, I had some critical "lib natives" missing in the wine prefix, so re-uploaded hoping you have an easier time spotting the error. If not - not much trouble and sorry to disturb you.
https://drive.google.com/open?id=1keEuQbi-d9AX3eRlvS2vQWQdGDUI--15

### Specs
Specs etc. stay the same. except for wine being 4.12.1 now and ofc llvm and mesa being newer versions.

Br, thanks and sorry for bothering, I think an updated issue is better than an orphan one ;-),
G

**Comment by CME42** [comment]
The trace is working fine on the latest master, can you please try it?
Get the latest build here: https://git.froggi.es/joshua/d9vk/-/jobs

**Comment by STiAT** [comment]
Can confirm, works with e062d9f0. Thanks!

**Comment by STiAT** [comment]
Side-Note, works on LLVM 8.0.0 and Mesa 19.0.6 too.

**Comment by sigzegv** [comment]
I'm not sure we can tell it's fixed yet, with d9vk ground texture are really too bright :

d9vk : 
![wow-1 12-d9vk](https://user-images.githubusercontent.com/6304596/62411573-3efe9f00-b5f5-11e9-98fb-172f9619de6a.png)

wined3d9 : 
![wow-1 12-wined3d](https://user-images.githubusercontent.com/6304596/62411575-432abc80-b5f5-11e9-8624-4a1f057c656e.png)

**Comment by STiAT** [comment]
I judged that to be light/shader issues rather than texture issues and therefore a different issue. To my knowledge not all D3D9 light/shadow/shader functions are implemented yet.

In any case, I'd judge that issue to be a different one to ground textures missing.

**Comment by sigzegv** [comment]
no problem I'll make another ticket for this.

**Comment by Joshua-Ashton** [comment]
I implemented lighting a few moments ago.

**Comment by STiAT** [comment]
Thanks Josh for the reply. I can confirm, lightning works as of 34b0e536 and looks good. Great work, thank you!
![Screenshot from 2019-08-04 02-59-23](https://user-images.githubusercontent.com/1781015/62418167-e7e3e300-b663-11e9-8c27-3f8db967d4ad.png)

Interestingly I've an issue on the loading screen with just one of those characters. That looks a bit weird ...

![Screenshot from 2019-08-04 03-01-59](https://user-images.githubusercontent.com/1781015/62418184-40b37b80-b664-11e9-94af-4c360371f006.png)

**Comment by Joshua-Ashton** [comment]
Loading screen looks fine on the trace I have? Could you provide one showcasing that issue?

**Comment by STiAT** [comment]
First of all, I'll provide what wine native shows, which is wrong too, sinces it misses the tabard with the heart:
![Screenshot from 2019-08-04 03-18-36](https://user-images.githubusercontent.com/1781015/62418328-a3a61200-b666-11e9-9e2b-e7761fb62640.png)

But yes, it's a "bit" less dark.

Ofc I did an apitrace for you, LLVM 8 and still Mesa 19.0.6, if you require new versions let me know and I'll try to reproduce on my testing install.
# API trace
https://drive.google.com/open?id=1OB6QzhA0-6F-RrRhr36RkprMrzeAlB9W

**Comment by STiAT** [comment]
In this case we're trying to find that one, I'm reopening, even though, it's not the original issue.

**Comment by sigzegv** [comment]
yes it's still a bit too dark
![wow-1 12-d9vk-dark](https://user-images.githubusercontent.com/6304596/62422506-0d98d880-b6b4-11e9-991e-1ce754ba6cf1.png)

**Comment by sigzegv** [comment]
@STiAT in my case with native it always matches windows coloring/lightning.

**Comment by Joshua-Ashton** [comment]
Should be fixed by

https://github.com/Joshua-Ashton/d9vk/commit/f637f64d28cf94a6647a49f518ef9138114b878e

Can you verify?

**Comment by STiAT** [comment]
The login screen yes, but still a lot darker than native wine in game. And I get funny light-bulbs moving on the ground in d9vk when zooming in&out.

Specs still the same, but d9vk-f637f64.

### API Trace (zooming in&out like on the screenshots)
https://drive.google.com/open?id=1Dykb3ApV6JKTfWQuOG97eURZNfU4KY8I

### Screenshots
![Screenshot from 2019-08-05 18-14-18](https://user-images.githubusercontent.com/1781015/62479195-2fc25180-b7ad-11e9-9300-583f6b9e4942.png)
![Screenshot from 2019-08-05 18-21-04](https://user-images.githubusercontent.com/1781015/62479498-e9212700-b7ad-11e9-95b3-326fe3805609.png)
![Screenshot from 2019-08-05 18-15-51](https://user-images.githubusercontent.com/1781015/62479197-318c1500-b7ad-11e9-9ac6-a1102b4f244e.png)
![Screenshot from 2019-08-05 18-16-10](https://user-images.githubusercontent.com/1781015/62479201-32bd4200-b7ad-11e9-8a2a-e69c49090c00.png)
![Screenshot from 2019-08-05 18-16-21](https://user-images.githubusercontent.com/1781015/62479206-33ee6f00-b7ad-11e9-8aa9-92b0a2869e97.png)

**Comment by sigzegv** [comment]
got the same lighting bulbs results here

![wow-1 12-spot-d9vk](https://user-images.githubusercontent.com/6304596/62480154-5f725900-b7af-11e9-8af3-f489cf18777b.png)
![wow-1 12-spot-wined3d](https://user-images.githubusercontent.com/6304596/62480159-613c1c80-b7af-11e9-946f-27c04f6c7a6a.png)


I noticed distant clipping fog effects are not present
![wow-1 12-d9vk](https://user-images.githubusercontent.com/6304596/62480180-7153fc00-b7af-11e9-88a0-c3371b30eb33.png)
![wow-1 12-wined3d](https://user-images.githubusercontent.com/6304596/62480183-731dbf80-b7af-11e9-9b0b-55b752065675.png)

**Comment by Joshua-Ashton** [comment]
Should be better now, can you try again with latest master?

**Comment by sigzegv** [comment]
You got it ! lightning seems to match

d9vk
![wow-1 12-d9vk](https://user-images.githubusercontent.com/6304596/62492780-cb64b980-b7cf-11e9-8577-bd4e85f2e38f.png)

wined3d
![wow-1 12-wined3d](https://user-images.githubusercontent.com/6304596/62492783-cef84080-b7cf-11e9-9ba8-32219da7235c.png)

The Last point are some missing reflection shaders ?  I suppose they are not part of this issue ?

d9vk
![wow-1 12-spot-d9vk](https://user-images.githubusercontent.com/6304596/62492866-edf6d280-b7cf-11e9-9370-8296e2358564.png)
wined3d
![wow-1 12-spot-wined3d](https://user-images.githubusercontent.com/6304596/62492871-f18a5980-b7cf-11e9-8662-8d797528eab6.png)

Do I open another issue for this and the clipping fov ?

**Comment by Joshua-Ashton** [comment]
Sure, atlhough I don't know what those issues are

**Comment by STiAT** [comment]
Hi,

That one certainly works, great work Josh, as always, I'm both, grateful and impressed how fast you got that one.

I think what @sigzegv actually means by "clipping issues" is rather a view distance/fog rendering issue. Can't be 100 % sure, but that's what I experience. Not sure that's even implemented yet API wise, nothing to do with ground textures or lighting for sure ;-).


### API Trace
Sorry for wandering around like an idiot, but I have tremendous input lag when running in debug mode, my PC isn't the best and I wanted to show the clipping in/out (as you use the records for reproducing, sorry for the length/size :p).
https://drive.google.com/open?id=1blpFOEPSjxLHTWq9wPEJgyxi7d7VSxJ9

### Screenshots
Wine
![Screenshot from 2019-08-06 00-56-42](https://user-images.githubusercontent.com/1781015/62500205-babf3e00-b7e5-11e9-8ed2-a815602c318a.png)

Wine with D9VK
![Screenshot from 2019-08-06 00-57-34](https://user-images.githubusercontent.com/1781015/62500228-c9a5f080-b7e5-11e9-97e3-47677bbcc787.png)

**Comment by Joshua-Ashton** [comment]
Yeah there is no fixed func fog yet

**Comment by STiAT** [comment]
Hey Josh,

that's what I thought. Separate issue on that one and you tag it once implemented so we can test it? Happy to open another one for that and finally close that one .. which got out of bounds anyway ;-).

**Comment by STiAT** [comment]
For the reflection thing in Thunder Bluff, I'll get to that trying to reproduce this / apitrace that on Wednesday or Thursday, won't be able to get to that before that.

**Comment by sigzegv** [comment]
I've made one ticket for ground specular issue https://github.com/Joshua-Ashton/d9vk/issues/288
