### ISSUE TITLE
Sonic Adventure 2 graphical issues

### ISSUE THREAD

**Issue by CartoonFan** [Joshua-Ashton/d9vk#292]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace.
DO NOT use DXVK together with apitrace!

### Software information
Sonic Adventure 2 (Steam 213610)

### System information
- GPU: GeForce GTX 960
- Driver: 430.34.0
- Wine version: 4.13 TKG
- DXVK version: https://github.com/Joshua-Ashton/d9vk/commit/b25eaf65e7731d42263b78d091de672cdc791e05

### Apitrace file(s)
https://drive.google.com/file/d/1MhdrCxRYA1gGxRN0Wuxi0Ak7thHXOLXT/view?usp=sharing

### Log files
- d3d9.log: [sonic2app_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3474388/sonic2app_d3d9.log)
- d3d11.log: N/A
- dxgi.log: N/A

Hello. Sonic Adventure 2 has a strange bug where the bottom of a train car appears above Sonic at various points in the first level.

The effect is pictured here:

D9VK:
![D9VK-20190804-183001](https://user-images.githubusercontent.com/29664894/62581194-488a4000-b85d-11e9-96a5-b6cf7bcec704.png)

Windows:
![sonic2app_Windows_2](https://user-images.githubusercontent.com/29664894/62581207-5344d500-b85d-11e9-8c0b-bf8395fab530.png)

I renamed the exe to be able to run the game (also needed on Wine), so that's why the actual log says Launcher.exe. Thanks for all your hard work.

EDIT: changed the trace to a tar.xz.

**Comment by Joshua-Ashton** [comment]
Can you see if its corrected as of latest commit?

**Comment by CartoonFan** [comment]
The bug is still reproducible for me with the current trace.

**Comment by Joshua-Ashton** [comment]
What's the name of the exe?

**Comment by CartoonFan** [comment]
The actual game is sonic2app.exe. Steam usually calls Launcher.exe and then crashes, and I renamed Launcher.exe to sonic2app.exe to avoid the crash.

**Comment by Joshua-Ashton** [comment]
Oh, that makes this much more complex then

**Comment by CartoonFan** [comment]
How do you mean?

**Comment by CartoonFan** [comment]
Thank you! On a side note, do you know why the issue is fixed in-game but not in the trace?

**Comment by Joshua-Ashton** [comment]
Because I did a workaround

**Comment by CartoonFan** [comment]
Ah, OK. I don't know what UB means, but thanks for taking the time to reply. I'm mainly curious whether I can trust a trace or if I have to check the actual game every time a new commit comes around. Thanks again!

**Comment by Joshua-Ashton** [comment]
Undefined behaviour yeah. It's putting NaNs in as float constant. We do the same as Intel drivers and -> 0 so we hit on the same bug.

**Comment by CartoonFan** [comment]
I think I kind of get it. At least, I remember that floats are intended to hold numbers, and I assume putting...not-numbers is bad. I guess putting a 0 instead makes the bug show up in the trace but not in the game itself, since the trace is doing...something else. Or something. I appreciate all this, though. I'm definitely not a programming ace by any means, so I'm just trying to do my best.
