### ISSUE TITLE
SWAT 4 lighting issues

### ISSUE THREAD

**Issue by CartoonFan** [Joshua-Ashton/d9vk#293]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace.
DO NOT use DXVK together with apitrace!

### Software information
SWAT 4 (GOG)

### System information
- GPU: Nvidia GeForce GTX 960
- Driver: 430.34.0
- Wine version:  4.13 TKG
- DXVK version: https://github.com/Joshua-Ashton/d9vk/commit/b25eaf65e7731d42263b78d091de672cdc791e05

### Apitrace file(s)
https://drive.google.com/file/d/1g4kMfCHT7UrwSqDo-8MtOY0Xo84VgLSG/view?usp=sharing (Around 2 GB compressed, 6 GB uncompressed)

### Log files
- d3d9.log: [Swat4_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3474425/Swat4_d3d9.log)

- d3d11.log: N/A
- dxgi.log: [Swat4_dxgi.log](https://github.com/Joshua-Ashton/d9vk/files/3474426/Swat4_dxgi.log)

Hello. SWAT 4 has some mild to moderate lighting issues, hopefully highlighted below.

Helmets, some weapons, and certain articles of clothing seem to be much darker than they should be:

D9VK:
![SWAT 4  d9vk  (6) ](https://user-images.githubusercontent.com/29664894/62582193-6c9b5080-b860-11e9-99b1-d7268e063e20.png)

![SWAT 4  d9vk  (12) ](https://user-images.githubusercontent.com/29664894/62582271-aec49200-b860-11e9-83ef-4aca82db8d10.png)

![SWAT 4  d9vk  (14) ](https://user-images.githubusercontent.com/29664894/62582322-dae01300-b860-11e9-82e1-23f99ae5e874.png)

Windows:
![SWAT 4  Windows  (2) ](https://user-images.githubusercontent.com/29664894/62582350-f5b28780-b860-11e9-9ae9-4e77d0aef392.PNG)

![SWAT 4  Windows  (5) ](https://user-images.githubusercontent.com/29664894/62582387-14b11980-b861-11e9-9eea-f19e445bc91c.PNG)

![SWAT 4  Windows  (8) ](https://user-images.githubusercontent.com/29664894/62582410-2c889d80-b861-11e9-9faa-50e2b7d02f8b.PNG)

Also, the lighting feels just a little off:

D9VK:
![SWAT 4  d9vk  (8) ](https://user-images.githubusercontent.com/29664894/62582505-8ab58080-b861-11e9-81ca-0f8495866881.png)

Windows:
![SWAT 4  Windows  (3) ](https://user-images.githubusercontent.com/29664894/62582526-9bfe8d00-b861-11e9-9bd7-0258e3fe4492.PNG)

The worst of it seems to be the from the "Optiwand" viewfinder device.

D9VK:
![SWAT 4  d9vk  (9) ](https://user-images.githubusercontent.com/29664894/62582611-ef70db00-b861-11e9-93e7-27dac0412c03.png)

Windows:
![SWAT 4  Windows  (4) ](https://user-images.githubusercontent.com/29664894/62582651-0c0d1300-b862-11e9-9e5b-f7819df86498.PNG)

Thanks and sorry for the pictures and the massive trace. Also, fog might be involved, so it may be related to #289, and if so, sorry in advance.

EDIT: Changed trace to tar.xz.

**Comment by Joshua-Ashton** [comment]
Should be fixed by f475fed4069998a3f38f8795db3e1b48a8f06c5d, can you confirm?

**Comment by CartoonFan** [comment]
With the current commit and apitrace, the viewfinder issue looks fixed, the lighting looks more or less fixed (the police headlights appear correctly), but the dark textures issue remains.

**Comment by tannisroot** [comment]
Can you check if you still encounter issues with latest master?

**Comment by CartoonFan** [comment]
Right, I'll take a look.

**Comment by CartoonFan** [comment]
Well, it looks fixed now.

Closing #293.
