### ISSUE TITLE
FHX (Ferentus, Herrcot, Xiones) Issues

### ISSUE THREAD

**Issue by cynicer** [Joshua-Ashton/d9vk#306]
We're a small group of developers reviving an old Korean MMO by reimplementing the game server. We're rather advanced on the server side, but still have issues with the old game client. The game is based on DX9 and GDI and runs on Windows 10, but has several issues (gradual frame drop, crashes on NVIDIA drivers and extreme frame drop on UI with lots of text). D9VK solves all of this issues, the game runs better than ever (great work, thanks!), but a few new problems arise (also see apitrace):

- ~~Lighting is rendered wrong~~ (Fixed as of 8490b27b)
- ~~Skybox is not rendered~~ (Fixed)
- ~~Mouse is "caught" in the game, until it reaches a UI element, where it can be moved freely. Makes it unuseable.~~ (Fixed by c424300a)
- Water reflections are completely flat
- ~~Fog is not drawn~~ (Fixed as of eba88d08)

It would be awesome if you guys were able to figures out the issue. This would give a couple hundreds of people the chance to enjoy the game smoothly.

With D9VK:
![Client_2019-08-17_10-24-07](https://user-images.githubusercontent.com/5718282/63208947-125d8380-c0db-11e9-95b7-55961ec15259.jpg)
![Client_2019-08-17_10-24-56](https://user-images.githubusercontent.com/5718282/63208948-12f61a00-c0db-11e9-8af0-d6c29e94ca2c.jpg)

Without D9VK:
![Client_2019-08-17_10-27-34](https://user-images.githubusercontent.com/5718282/63208953-1b4e5500-c0db-11e9-8a41-7975e62bcaa6.jpg)
![Client_2019-08-17_10-28-11](https://user-images.githubusercontent.com/5718282/63208954-1b4e5500-c0db-11e9-90a6-28270547ca4c.jpg)

### Software information
FHX (Ferentus, Herrcot or Xiones) released in 2004 and closed in 2008.

### System information
- GPU: NVIDIA GTX 1080
- Driver: 430.86
- Wine version: - (latest Windows 10) 
- DXVK version: master (2b6f011160be478fdc0fe65904e9d7698776ca05)

### Apitrace file(s)
https://drive.google.com/open?id=1vVGpp30OkO32Cf7zEcv60DxgfKLdYu4F

### Log files
- d3d9.log: 
[Client_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3511811/Client_d3d9.log)

- d3d11.log: -
- dxgi.log: - (empty)

**Comment by cynicer** [comment]
While going through the logs I just noticed that the fog rendering is missing as well. So I guess the problems are:
- Missing render states for fog (D3DRS_FOGDENSITY, D3DRS_FOGCOLOR, D3DRS_FOGTABLEMODE, D3DRS_FOGSTART, D3DRS_FOGEND, D3DRS_DITHERENABLE)
- Missing environmental lighting support (D3DTOP_BUMPENVMAPLUMINANCE)
- Missing AL16 and R16 format support (Unknown format encountered: 909200449 warn: ConvertFormat: Unknown format encountered: 909201952)

The last one confuses be, as you guys already seem to have included support for those formats in https://github.com/Joshua-Ashton/d9vk/pull/155

Another question is: what causes the mouse to not work properly ingame?

**Comment by cynicer** [comment]
As of eba88d08 the fog renders now seemingly correctly.

![Client_2019-08-22_22-16-14](https://user-images.githubusercontent.com/5718282/63546669-9e800880-c52a-11e9-881e-02e1fc00170a.jpg)

Thanks for your effort!

**Comment by cynicer** [comment]
Lighting seems now correct on master. The sky is still missing and the mouse is still almost unusable (jumps back to old location). Very good work so far! 

![Client_2019-08-25_13-40-25](https://user-images.githubusercontent.com/5718282/63649452-36097500-c73e-11e9-9ceb-15a62dd57c0c.jpg)

[Client_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3538090/Client_d3d9.log)

**Comment by Joshua-Ashton** [comment]
Is this still an issue?

**Comment by cynicer** [comment]
Retested with master (d6f5ec8e3d92fc3261a6952aa10aa474fbee26db). The mentioned issues (missing/wrong sky and water reflections and still present). Do you need any data? Is there anything I can provide which helps?

**Comment by CME42** [comment]
I guess the flat water reflection is probably related to:
warn:  D3DTOP_BUMPENVMAPLUMINANCE: not implemented

**Comment by cynicer** [comment]
Are these tickets still being worked on? Or should we reopen them in DXVK?

**Comment by Joshua-Ashton** [comment]
Its fine here

**Comment by misyltoad** [comment]
Hi, this should be fixed in master

builds: https://git.froggi.es/doitsujin/dxvk/-/jobs

**Comment by cynicer** [comment]
Sky looks good now, water reflections still don't work correctly (they appear completely flat, originally they had ripples). Also the minimap does not render correctly anymore (top right in the screenshot), this used to work already.

![grafik](https://user-images.githubusercontent.com/5718282/72671792-0726cf00-3a50-11ea-90e6-7768c78ad963.png)

**Comment by cynicer** [comment]
I narrowed the minimap rendering issue (see screenshot in post above: transparent and not round). It's caused by commit 312905e8a34485dfb88e2c764d0d7bfaab47de04.

So the open issues atm for us are:
- ~~Minimap is rendered incorrectly (after 312905e8a34485dfb88e2c764d0d7bfaab47de04)~~
- Water reflections are missing -> completely flat

**Comment by cynicer** [comment]
Confirming minimap works again after 792c74e, thanks!

**Comment by misyltoad** [comment]
Reflection stuff should be fixed as of https://github.com/doitsujin/dxvk/commit/310ab6da640b0849c54bdc2f40b81d0327344f31

**Comment by cynicer** [comment]
Seems to be working fine, thank you very much for your effort!
All major things are working now for us, I got some minor things, but I will test and document them in a new issue in DXVK :-)
