### ISSUE TITLE
GZDoom Builder doesn't display alphas/transparency of textures

### ISSUE THREAD

**Issue by polyzium** [Joshua-Ashton/d9vk#307]
GZDoom Builder-Bugfix crashes on map load/creation. On WineD3D it works perfectly, except there is no transparency in 3D mode, which sucks. So I tried D9VK, but I get this.

### Software information
GZDoom Builder-Bugfix R3060

### System information
- GPU: NVIDIA GeForce GTX 650
- Driver: nvidia-dkms 430.40-3
- Wine version: 4.13
- D9VK version: Release 0.13f

### Apitrace file(s)
- [Link](https://drive.google.com/file/d/1r5NTZkzIy0N8juDVx0qfoNH795WpaKbq/view?usp=sharing)

### Log files
- d3d9.log: [Builder_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3512051/Builder_d3d9.log)
- d3d11.log: N/A
- dxgi.log: N/A

**Comment by K0bin** [comment]
0.13f is a bit old at this point. Can you try compiling the latest master and try that?

Your apitrace was made with D9VK. It ends before the call that caused the crash. Please make one with WineD3D or preferably on Windows. Also make sure to add the Wine terminal output.

**Comment by polyzium** [comment]
I think I forgot to disable D9VK in Lutris before making the trace. I'm using Arch so I'll have to wait a long time for MinGW GCC to compile, so I grabbed the latest passed build from [here](https://git.froggi.es/joshua/d9vk/-/jobs). Unfortunately, even that build still makes GZDB crash.
[Trace](https://drive.google.com/open?id=1jg65S8KLUc_W4Iy6bqO2vpgIbeT1iqTs)
[Log, with that D9VK build](https://github.com/Joshua-Ashton/d9vk/files/3512092/Builder_d3d9.log)

**Comment by K0bin** [comment]
> Unfortunately, even that build still makes GZDB crash.

Does Builder work with WineD3D (without apitrace)?

> Trace

Same thing as the original trace. It doesn't have the call that causes the crash because it ends before that.

> Log, with that D9VK build

That's the D9VK log again. It doesnt show anything interesting. Please post the terminal output.

**Comment by polyzium** [comment]
>Does Builder work with WineD3D (without apitrace)?
Read the first line of my issue.
>Same thing as the original trace. It doesn't have the call that causes the crash because it ends before that.
I do not understand; do you want a trace with OR without D9VK? I disabled D9VK in Lutris before making the trace.
>That's the D9VK log again. It doesnt show anything interesting. Please post the terminal output.
I'm using Lutris because GZDB is very error-ey on vanilla Wine. I can't do that.

**Comment by K0bin** [comment]
I want a trace without D9VK. Your second trace crashes at the exact same spot as the first one though.

IIRC Lutris has a button to show the terminal output of the last thing you ran.

**Comment by polyzium** [comment]
>I want a trace without D9VK. Your second trace crashes at the exact same spot as the first one though.

This is weird. I ran it after disabling D9VK; all I did is make a new map, add a resource, wait for the layout window to appear, then exit.
I don't know how can you tell if that trace is D9VK's or WineD3D's. Looking at it with a hex editor doesn't tell anything. I made both, for comparison purposes.
[WineD3D](https://drive.google.com/open?id=1pEHBGv_k49n6g4I0mCmFBaN1OZIQ2bL7)
[D9VK](https://drive.google.com/open?id=1LLBb4TSOkOdjcXqrOVPrcBuI9g9PFx-u)

>IIRC Lutris has a button to show the terminal output of the last thing you ran.

It's "Show logs". I'm sure you won't find anything interesting there, it's just several lines.
However, I tried by exporting WINEPREFIX in a terminal and running the app.
[Terminal log](https://hastebin.com/afebomecad.rb)

**Comment by K0bin** [comment]
Mhm, it seems apitrace doesn't really work for GZDoom Builder. All your traces are just <10mb and they all seem to be incomplete. At least apitrace complains when replaying: `warning: unexpected end of file while reading trace`.
The last D9VK trace doesn't crashes with the first api call.

> It's "Show logs". I'm sure you won't find anything interesting there, it's just several lines.
> However, I tried by exporting WINEPREFIX in a terminal and running the app.

That's what I meant. Those logs were made with WineD3D though, right? I'd need the logs with D9VK. (Yes, I know it's a bit confusing.)

**Comment by polyzium** [comment]
Update: ran GZDB in terminal again, this time with DXVK; after loading the map, this message appears:
```
003b:fixme:vulkan:X11DRV_vkCreateWin32SurfaceKHR Application requires child window rendering, which is not implemented yet!
```

**Comment by K0bin** [comment]
Ah, that's what I thought.

It's a Wine problem that can't be fixed in DXVK/D9VK.
[Here's an experimental patch that should make it work.](https://www.winehq.org/pipermail/wine-devel/2019-July/148639.html)

**Comment by polyzium** [comment]
That made it work, thanks.
But I still don't get transparency and it's more laggier than WineD3D. I also found out that there's [an OpenGL port](https://github.com/dpjudas/GZDoom-Builder-Bugfix/tree/slimgl), but there are no binaries provided and I don't have a copy of Windows installed to build it, so I'm DOOMed (pun intended)... Idk what to do.

**Comment by Joshua-Ashton** [comment]
I imagine this is a fixed function app, can you please try a newer build here? We had quite a lot fixes in that regard recently

https://git.froggi.es/joshua/d9vk/-/jobs

**Comment by polyzium** [comment]
I downloaded the latest passed build (3 days ago) from there. It works, but still no transparency.

**Comment by Joshua-Ashton** [comment]
The trace is invalid and I was unable to replicate your issue with the GZDoom Builder myself... Any specific textures/whatever I should look out for?

**Comment by axredneck** [comment]
@Joshua-Ashton 
> I was unable to replicate your issue with the GZDoom Builder myself

Does alpha channel in GZDB work for you?

**Comment by Joshua-Ashton** [comment]
Well, it works fine for the missing texture texture

**Comment by polyzium** [comment]
Downloaded the latest build again. Still no alpha (white solid box around the crosshair)
![image](https://user-images.githubusercontent.com/22579935/63882665-2490c900-c9db-11e9-8625-4ccd0577580a.png)

**Comment by wongit** [comment]
Seconding polyziums experience with the borked alpha. Running r3097 32bit from Lutris (attempted various tweaks but no luck).

**Comment by Joshua-Ashton** [comment]
Can you try in the latest master? I fixed some alpha issues in fixed function games recently? A working apitrace if that doesn't work would be helpful

**Comment by polyzium** [comment]
Still no alpha. [Trace](https://github.com/Joshua-Ashton/d9vk/files/3853606/Builder.20.trace.tar.gz)

**Comment by Joshua-Ashton** [comment]
Replaying that trace also shows the issue for me, even in native d3d9.

I'm assuming this is a D9VK trace because of that. Could you make an apitrace with wined3d please?

**Comment by Joshua-Ashton** [comment]
![image](https://user-images.githubusercontent.com/21316711/69600663-63014880-1009-11ea-8291-f689e6782723.png)

Trying out GZDoom Builder myself, and it works fine...

**Comment by Joshua-Ashton** [comment]
![image](https://user-images.githubusercontent.com/21316711/69600699-7f9d8080-1009-11ea-8c23-21b024a2fff9.png)
works fine on NVidia too...

**Comment by Joshua-Ashton** [comment]
![image](https://user-images.githubusercontent.com/21316711/69600769-c2f7ef00-1009-11ea-866b-9cae2b262543.png)

Works fine on the bugfix release too

**Comment by Joshua-Ashton** [comment]
This isn't my bug.
It only happens on Wine, and it isn't related to `d3dcompiler`/`d3dx9`.

You should make an issue report on the Wine bug tracker.

**Comment by superlazyname** [comment]
@Joshua-Ashton can you give me more information about your setup? (WINE version, d9vk version, etc)

**Comment by Joshua-Ashton** [comment]
@superlazyname 

Hello, just using wine-staging on Arch + wine-mono. I also installed native d3dx9 and d3dcompiler but it didn't change anything.

This isn't a D9VK bug as it works fine with GZDoom Builder Bugfix on Windows. But I was using master.

If you manage to workaround on your end lmk and I'll try and forward that info the the appropriate people or patch it myself.

There's a lot of Wine errors wrt. GDI colors but I'm not sure if thats related.

**Comment by superlazyname** [comment]
@Joshua-Ashton ah, I see, so you were using d9vk on Windows in your screenshots? Yeah, now that I look at it closer that does look like Windows title bars. 

In my case gzdb does not render at all with wined3d (corrupted visuals in 2d and 3d modes, I don't think it's even drawing to the screen at all) . I am going to try d9vk next just to see if it makes any difference.

**Comment by superlazyname** [comment]
Update, https://bugs.winehq.org/show_bug.cgi?id=45277#c32 seems to be the related WINE bug, unfortunately this issue is still not resolved; I tried a couple of the commits mentioned in the bug  tracker but it still seemed to consistently fail with:

> 0009:fixme:vulkan:X11DRV_vkCreateWin32SurfaceKHR Application requires child window rendering, which is not implemented yet!
terminate called after throwing an instance of 'dxvk::DxvkError'

I'm guessing that this means that there's no way to use d9vk through WINE?

**Comment by Joshua-Ashton** [comment]
There's a child window patch floating about. Check tkgs pkgbuilds.

Has other bugs when used under Wine though.
