### ISSUE TITLE
Cannot open window full screen

### ISSUE THREAD

**Issue by shijiediyo** [Joshua-Ashton/d9vk#318]
Hello big man, can you add a window full screen? I play BNS, I use the latest file, only full screen, but full screen typing has no status bar. The settings in the game are useless. Can you modify them or send me a copy alone? This is my mailbox 1090491684@qq.com. Thank you very much. Don't mind if English is a little bad.

From China

**Comment by Joshua-Ashton** [comment]
I have no idea what BNS is, sorry. :<

**Comment by shijiediyo** [comment]
Blade & Soul 
I play this game, the game is set with windowing, full screen windowing, full screen, after using the plug-in, the game default full screen, can't windowing full screen, and then input the text, don't know what text input

**Comment by Joshua-Ashton** [comment]
Can you show me with a picture?

**Comment by shijiediyo** [comment]
Thank you for making such a good plug-in, I also recommended to my friends, I also consulted the Internet, full-screen mode input text can not appear in the selection bar, there are many online games are also dx9, if not in the game normal communication, quite painful, the picture may not be very intuitive, so I made a video. I don't know if you can link to this website. I translate what I want to say into English by means of translation software. The translation may not be very good. Don't mind.


https://www.bilibili.com/video/av65173600/

**Comment by shijiediyo** [comment]
I think it's the plug-in that forces the full screen to be turned on.

**Comment by shijiediyo** [comment]
[∧.∧]

**Comment by shijiediyo** [comment]
Hello, big man, I modified the resolution, 2560*1080 modified 1920*1080, default full screen problem solved, haha

**Comment by Joshua-Ashton** [comment]
I implemented present regions btw, which may also help with the issue

**Comment by shijiediyo** [comment]
big man ，Full screen problem is still not solved effectively，This is the log of d3d9 file. You can check it. At the end, the screen resolution and 《Windows: ture》 are written.
  

 Game: client64.exe
info:  DXVK: d9vk-0.20-frogcookie
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  D3D9: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  Radeon RX 580 Series:
info:    Driver: 2.0.99
info:    Vulkan: 1.1.113
info:    Memory Heap[0]: 
info:      Size: 7936 MiB
info:      Flags: 0x3
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 7904 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 256 MiB
info:      Flags: 0x3
info:      Memory Type[2]: Property Flags = 0x7
info:  Process set as DPI aware
info:  Game: client64.exe
info:  DXVK: d9vk-0.20-frogcookie
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  D3D9: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  Radeon RX 580 Series:
info:    Driver: 2.0.99
info:    Vulkan: 1.1.113
info:    Memory Heap[0]: 
info:      Size: 7936 MiB
info:      Flags: 0x3
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 7904 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 256 MiB
info:      Flags: 0x3
info:      Memory Type[2]: Property Flags = 0x7
info:  Process set as DPI aware
info:  Device properties:
info:    Device name:     : Radeon RX 580 Series
info:    Driver version   : 2.0.99
info:  Enabled device extensions:
info:    VK_AMD_memory_overallocation_behavior
info:    VK_AMD_shader_fragment_mask
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_host_query_reset
info:    VK_EXT_memory_priority
info:    VK_EXT_shader_stencil_export
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_create_renderpass2
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_depth_stencil_resolve
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 0
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 0
info:    logicOp                                : 0
info:    multiDrawIndirect                      : 0
info:    drawIndirectFirstInstance              : 0
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 0
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 0
info:    shaderImageGatherExtended              : 0
info:    shaderStorageImageExtendedFormats      : 1
info:    shaderStorageImageReadWithoutFormat    : 0
info:    shaderStorageImageWriteWithoutFormat   : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 0
info:    shaderInt64                            : 0
info:    variableMultisampleRate                : 0
info:  VK_EXT_conditional_rendering
info:    conditionalRendering                   : 0
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_host_query_reset
info:    hostQueryReset                         : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 1
info:  VK_EXT_shader_demote_to_helper_invocation
info:    shaderDemoteToHelperInvocation         : 0
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 0
info:    geometryStreams                        : 0
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 0
info:    vertexAttributeInstanceRateZeroDivisor : 0
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 2
info:  DXVK: Read 33248 valid state cache entries
info:  DXVK: Using 9 compiler threads
info:  D3D9DeviceEx::ResetEx:
info:    Requested Presentation Parameters
info:      - Width:              1280
info:      - Height:             768
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::Unknown
info:      - Windowed:           true
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_R8G8B8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  1280x768
info:    Image count:  2
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_POINTSIZE
info:  Game: client64.exe
info:  DXVK: d9vk-0.20-frogcookie
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  D3D9: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  Radeon RX 580 Series:
info:    Driver: 2.0.99
info:    Vulkan: 1.1.113
info:    Memory Heap[0]: 
info:      Size: 7936 MiB
info:      Flags: 0x3
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 7904 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 256 MiB
info:      Flags: 0x3
info:      Memory Type[2]: Property Flags = 0x7
info:  Process set as DPI aware
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_R8G8B8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  1280x768
info:    Image count:  2
info:  D3D9DeviceEx::ResetEx:
info:    Requested Presentation Parameters
info:      - Width:              1920
info:      - Height:             1080
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::Unknown
info:      - Windowed:           true
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_R8G8B8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  1920x1080
info:    Image count:  2
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_R8G8B8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  2560x1061
info:    Image count:  2
info:  D3D9DeviceEx::ResetEx:
info:    Requested Presentation Parameters
info:      - Width:              2560
info:      - Height:             1080
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::Unknown
info:      - Windowed:          ture
info:  D3D9DeviceEx::ResetEx:
info:    Requested Presentation Parameters
info:      - Width:              2560
info:      - Height:             1061
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::Unknown
info:      - Windowed:           ture
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_R8G8B8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  2560x1061
info:    Image count:  2
info:  D3D9DeviceEx::ResetEx:
info:    Requested Presentation Parameters
info:      - Width:              2560
info:      - Height:             1080
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::Unknown
info:      - Windowed:           ture
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_R8G8B8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  2560x1080
info:    Image count:  2
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub
warn:  D3D9DeviceEx::SetDialogBoxMode: Stub

**Comment by Joshua-Ashton** [comment]
Unfortunately this game relies on ``SetDialogBoxMode`` which is impossible for me to implement.

You will have to play in Windowed mode. Sorry.

**Comment by Joshua-Ashton** [comment]
If you need to workaround you can use the ``DXVK_FORCE_WINDOWED=1`` environment variable.

**Comment by Joshua-Ashton** [comment]
If you need to force windowed mode, you can use the environment variable ``DXVK_FORCE_WINDOWED=1``.

**Comment by shijiediyo** [comment]
Excuse me, this d3d9.dll file you encapsulated needs to be opened with that software. I found DXVK_FORCE_WINDOWED=1. I can't open it with c++.

**Comment by shijiediyo** [comment]
Excuse me, this d3d9.dll file you encapsulated needs to be opened with that software. I found DXVK_FORCE_WINDOWED=1. I can't open it with c++, I use win10.

**Comment by Joshua-Ashton** [comment]
Can you please try with https://github.com/Joshua-Ashton/d9vk/commit/65aa02f288c80e0cd97c9d3622a375dca5a75dc7

The build job is available here if you want a compiled version:
https://git.froggi.es/joshua/d9vk/-/jobs/897
