### ISSUE TITLE
Payday: the heist - floor and wall textures are blocky and pixelated.

### ISSUE THREAD

**Issue by Shished** [Joshua-Ashton/d9vk#38]
Wall and floor has incorrect textures. Game draws solid color squares which are covered in digital camo-like pixelated texture. Pixels are moving all the time.
https://i.imgur.com/knqF9sE.jpg

### Software information
Latest Steam version, any settings.

### System information
- GPU: GTX 1060
- Driver: 418.52.03
- Wine version: vanila 4.6
- DXVK version: git master

### Apitrace file(s)
https://drive.google.com/open?id=1sGgfHyjobyi6jNTKiEZb9_Tima6x-tsN

### Log files
- d3d9.log: https://pastebin.com/ur5Qqbm0

**Comment by Joshua-Ashton** [comment]
Likely a garbage shader somehow

**Comment by money123451** [comment]
not a issue for me
![20190422050318_1](https://user-images.githubusercontent.com/12605368/56493787-c6f5e880-64df-11e9-8e47-70d37f801a10.jpg)

**Comment by Joshua-Ashton** [comment]
Can you see if
```
d3d9.customVendorId = 1002
d3d9.cusutomDeviceId = 687f
```
in dxvk.conf makes the issue go away?

**Comment by Shished** [comment]
Nope, the problem still exists.

![https://i.imgur.com/nNQhbV1.jpg](https://i.imgur.com/nNQhbV1.jpg)

dxvk.conf was loaded properly
```
info:  Found config file: dxvk.conf
info:  Effective configuration:
info:    d3d9.customDeviceId = 687f
info:    d3d9.customVendorId = 1002
```

**Comment by Joshua-Ashton** [comment]
Interesting how nvidia's driver is handling that differently

**Comment by Joshua-Ashton** [comment]
Can you try against latest master? This should be fixed now.

**Comment by Shished** [comment]
Sadly, this problem still presents.

![https://i.imgur.com/clhf67f.jpg](https://i.imgur.com/clhf67f.jpg)

**Comment by Joshua-Ashton** [comment]
Closed by a63208b17d74285e0b18856c4c3a041d1d14162c

**Comment by Shished** [comment]
Can confirm, this problem was fixed.
![https://i.imgur.com/Tbm579B.jpg](https://i.imgur.com/Tbm579B.jpg)
