### ISSUE TITLE
Battlefield 2 → crash when "Lightning" and "Dynamic Shadows" are set to high + bad transparency

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#415]
with d9vk:
https://imgur.com/InHs1gi

### System information
- GPU: Nvidia GT 730M
- Driver: 435.21
- Wine version: Proton 4.11
- DXVK version: #894

### Apitrace file(s)
https://mega.nz/#!ez4i2I6J!RxDrf-ZPboOqCQ_Vusmk2U1hDVjJIv9ofszpQ9WQIYE

### Log files
[battlefield2-grass.log](https://github.com/Joshua-Ashton/d9vk/files/3694894/battlefield2-grass.log)

**Comment by d10sfan** [comment]
I think that happens on wine as well. Some others reported that issue with certain video cards on windows and provided a fix. 

If you look at post 11 on http://www.battlefieldsingleplayer.com/forum/index.php?showtopic=16430, it provides a replacement shader zip that fixes the problem.

I tried the same fix with d9vk and it's looking good for me now

**Comment by NerosTie** [comment]
I can't register (an error about the security code...). Can you send the zip file here?

**Comment by d10sfan** [comment]
[shaders_client.zip](https://github.com/Joshua-Ashton/d9vk/files/3694962/shaders_client.zip)
Thia should be it

**Comment by NerosTie** [comment]
Thanks. Yes, it solves the issue.
@Joshua-Ashton Is something can be done with d9vk without this workaround?

**Comment by d10sfan** [comment]
It looks like there may have been a regression somewhere between 78dde4bf38b2aba9b3a4ff3d906518cd8dadf716 and the most recent commit. I downloaded the latest from the pipeline and noticed black lines appearing on the ground. Reverting back to that commit looks to have fixed it.

**Comment by NerosTie** [comment]
I can confirm.
https://imgur.com/A3wxjJP

**Comment by Joshua-Ashton** [comment]
The game does its lighting pass, then tries to render the same thing over the top with LESS_EQUAL

**Comment by fermmm** [comment]
> I think that happens on wine as well. Some others reported that issue with certain video cards on windows and provided a fix.
> 
> If you look at post 11 on http://www.battlefieldsingleplayer.com/forum/index.php?showtopic=16430, it provides a replacement shader zip that fixes the problem.
> 
> I tried the same fix with d9vk and it's looking good for me now

That is not a proper solution, if you replace these files you cannot play multiplayer anymore, because the multiplayer anti cheat system does not allow changes in game files

**Comment by d10sfan** [comment]
> > I think that happens on wine as well. Some others reported that issue with certain video cards on windows and provided a fix.
> > If you look at post 11 on http://www.battlefieldsingleplayer.com/forum/index.php?showtopic=16430, it provides a replacement shader zip that fixes the problem.
> > I tried the same fix with d9vk and it's looking good for me now
> 
> That is not a proper solution, if you replace these files you cannot play multiplayer anymore, because the multiplayer anti cheat system does not allow changes in game files
> 
> I was waiting for d9vk to enable a proper fix for this problem

At least for me, I wasn't trying to show that as a "proper" solution, simply a workaround that would make single player work (how I mainly play) and possibly provide insight into what might be happening for the D9VK devs (in case the difference in shaders might be interesting to see).

**Comment by NerosTie** [comment]
The shadows are now fixed thanks to DXVK 1.5.1 ! 🥳

![Screenshot_20200110_002412](https://user-images.githubusercontent.com/4572452/72113131-e2d83d80-333f-11ea-8ee0-246585f4ecdd.png)


But the grass is still a grid of points (you can see it on the screenshot)

**Comment by fermmm** [comment]
I'm trying with DXVK 1.5.1 and D9VK 0.40.1 and still seeing most of the same glitches:

![image](https://user-images.githubusercontent.com/3660373/72225639-73906280-3566-11ea-8bb5-2cfad17880d4.png)

![image](https://user-images.githubusercontent.com/3660373/72225716-6f187980-3567-11ea-9e32-9efdf96ee36a.png)

![image](https://user-images.githubusercontent.com/3660373/72225739-aedf6100-3567-11ea-8196-2e0ebc69d6ce.png)

![image](https://user-images.githubusercontent.com/3660373/72225771-ffef5500-3567-11ea-8f72-488896c1fc92.png)

Also when configuring all grahic effects to the highest quality I get a crash with this error when loading the map:
![image](https://user-images.githubusercontent.com/3660373/72225793-3a58f200-3568-11ea-961f-d6b354ddd248.png)

**Comment by NerosTie** [comment]
What's the version of your driver? Nvidia?

**Comment by fermmm** [comment]
> What's the version of your driver? Nvidia?
> 
> You shouldn't use D9VK 0.40.1, it's outdated.

This is my driver:
![image](https://user-images.githubusercontent.com/3660373/72225855-f1ee0400-3568-11ea-8a74-a64db58ea4a1.png)

I'm using D9VK 0.40.1 because is the latest avaiable in Lutris at this time

**Comment by NerosTie** [comment]
Well, that's because you are using D9VK. DXVK 1.5.1 is available in Lutris.

The releases of D9VK alone will be forever outdated. Now, it's bundled with DXVK.

I recommend you to use this: https://git.froggi.es/doitsujin/dxvk/-/jobs
It's compiled with the latest commits.

**Comment by fermmm** [comment]
I tried with DXVK only and I see the progress. 

Only this glitch is still happening in the medium quality preset:
![image](https://user-images.githubusercontent.com/3660373/72225639-73906280-3566-11ea-8bb5-2cfad17880d4.png)

Also this error eppeared randomly while playing when I increased graphic quality a bit:
![image](https://user-images.githubusercontent.com/3660373/72226105-01228100-356c-11ea-83a8-a99319b237e0.png)

When I set high graphic quality preset the same out of memory error eppeared:
![image](https://user-images.githubusercontent.com/3660373/72225793-3a58f200-3568-11ea-961f-d6b354ddd248.png)

I'll try to update my drivers and try again


> Well, that's because you are using D9VK. DXVK 1.5.1 is available in Lutris.
> 
> The releases of D9VK alone will be forever outdated. Now, it's bundled with DXVK.
> 
> I recommend you to use this: https://git.froggi.es/doitsujin/dxvk/-/jobs
> It's compiled with the latest commits.
> 
> **Edit**: also, update your driver, it's oudated too (5 months old!)

I tried with DXVK only and I see the progress, only this glitch is still happening:



The out of memory error in high quality still happens.
Also this error eppeared randomly when I increased the graphic quality a bit:

![image](https://user-images.githubusercontent.com/3660373/72226105-01228100-356c-11ea-83a8-a99319b237e0.png)

I'll try to update the drivers and try again

**Comment by Joshua-Ashton** [comment]
Please use native d3dcompiler and d3dx9s

**Comment by fermmm** [comment]
> Please use native d3dcompiler and d3dx9s

I don't have  d3dx9s in the autocomplete list, is that ok?
![image](https://user-images.githubusercontent.com/3660373/72228619-28d31280-3587-11ea-9463-89e584284550.png)

I added it anyway and I see the same out of memory error:
![image](https://user-images.githubusercontent.com/3660373/72228788-78660e00-3588-11ea-8b2f-20e015607f6f.png)

In medium quality still seeing the black spots on the terrain

**Comment by NerosTie** [comment]
In my case, I don't have you error message. The game just crashes during the shaders optimization.
More specifically, it crashes when "Lightning" and "Dynamic Shadows" are set to high ([pic](https://images.pcgamingwiki.com/e/ee/Secret_Files_Tunguska_-_configuration_tool_settings.png))

**Comment by fermmm** [comment]
> In my case, I don't have you error message. The game just crashes during the shaders optimization.
> More specifically, it crashes when "Lightning" and "Dynamic Shadows" are set to high ([pic](https://images.pcgamingwiki.com/0/06/Battlefield_2_Video.png))

To see the error message you have to run the game in wondowed mode, it seems to be the same problem

**Comment by NerosTie** [comment]
The grass is fixed!

But the game still crashes when "Lightning" and "Dynamic Shadows" are set to high, so I leave it open.

**Comment by misyltoad** [comment]
Is there a trace for that issue?

**Comment by ViNi-Arco** [comment]
Hello, Good night, Solved in which version of DXVK ?, I still have rendering problems:

![BF2-Print03](https://user-images.githubusercontent.com/57958460/75123489-942ffa00-5686-11ea-8a6e-98bee2079c5b.png)

**Comment by NerosTie** [comment]
With DXVK 1168 (https://git.froggi.es/doitsujin/dxvk/-/jobs)

**Comment by ViNi-Arco** [comment]
Thanks Neros, have a nice day

**Comment by ViNi-Arco** [comment]
I tested it here and... it didn't work for me :(

![2020-02-24-123559_1440x900_scrot](https://user-images.githubusercontent.com/57958460/75168573-dfd5b880-5705-11ea-8641-7f654788c5ff.png)

**Comment by NerosTie** [comment]
You are right, it's not fixed. Maybe I was dreaming :-(

**Comment by NerosTie** [comment]
Everything looks good now 🥳

**Comment by fermmm** [comment]
@NerosTie I still get the crash on DXVK 1.6 when the graphics are set to high, also tried the latest #1259 buid, but the same happens.
![image](https://user-images.githubusercontent.com/3660373/79697986-37068e00-825c-11ea-925c-bfccb228844d.png)

If you want to try yourself this is the game installer I use:
https://drive.google.com/uc?id=1jBCMUz3LYQpVyYC4rDwdwxG1OJP3a6x4&export=download
With this launcher:
https://www.bf2hub.com/home/downloads.php

You can use the launcher to run the game in window mode, that shows the error instead of just crashing to desktop

**Comment by NerosTie** [comment]
Open a new issue, mine is fixed. Yours is not related, so I'm closing this one.

**Comment by HolimaX** [comment]
I am seeing weird crashes for ages with certain Video settings. See my winehq bug report: https://bugs.winehq.org/show_bug.cgi?id=46247
Now trying to see what configs do work.
Using wine-staging 6.6 and latest dxvk (1.81) on Fedora 33.

**Comment by K0bin** [comment]
It's a different bug, make a new issue for that and provide the necessary info to debug it.

That bug report on WineHQ doesn't even use DXVK according to the logs.
