### ISSUE TITLE
Halo CE → Wack specular

### ISSUE THREAD

**Issue by gbMichelle** [Joshua-Ashton/d9vk#427]
Trace 1: Shield effect:
d3d9: https://www.youtube.com/watch?v=etIv_EfdWKc
d9vk: https://www.youtube.com/watch?v=-wEsYBllnTw

Trace 2: Headlights, red decal, shadows:
d3d9: https://i.imgur.com/6s12rxI.png
d9vk: https://i.imgur.com/HcO1Tof.png

### Software information
Halo Custom Edition, Max graphical settings, version 1.10.

### System information
- GPU: GTX 1060 3GB
- Driver: 435.21
- Wine version: Lutris 4.12
- D9VK version: 2a384def

### Apitrace file(s)
NOTE: These traces are black at IDirect3DDevice9::Present. But at IDirect3DDevice9::EndScene they have the screen in PS_RESOURCE_LEVEL_0.
Trace 1 should have a good frame to check out the effect at 183.
Trace 2 should be good somewhere around the middle.
Both are kept small by the fact that I used the game's scripting to set up scenes that show the shaders right at game start.
- https://drive.google.com/open?id=1DYNwd4kGV5LVF0JRurwCfz4Y-oTLdWRR

### Log files
- d3d9.log: https://pastebin.com/eCfY2Xr5

**Comment by Joshua-Ashton** [comment]
Given the fact that I own this game, can you tell me what map it is?

**Comment by gbMichelle** [comment]
Ah, well everything in trace 2 should be visible in Bloodgulch near red base.
The first trace I could compile a map that just spawns you in front of a dude with a shield that perpetually has this effect going on it.
If you need the dynamic light problem to be really visible then load of Damnation and fire the plasma pistol.

**Comment by gbMichelle** [comment]
Here is a multiplayer map that spawns you right in front of an elite biped that has it's shields set up to constantly be flaring.
https://drive.google.com/open?id=12A0ZVtRHfhc1_7BgrKTP05YCmAfAiJUc

**Comment by gbMichelle** [comment]
Edited my comments a little to make stuff more clear.

**Comment by gbMichelle** [comment]
Improvement: It seems that the decal issue is fixed now. 
![Screenshot_20191108_085034](https://user-images.githubusercontent.com/24233409/68459214-09c1a880-0205-11ea-96a7-5358eb1b6d64.png)

**Comment by Joshua-Ashton** [comment]
Can this be re-tested? I made some changes that should hopefully fix this issue (can't test on the trace for obvious reasons)

**Comment by jacobbrett** [comment]
I just tested with aa8d4979. I'm using an RX 580.

The following are still broken:
- Shield effect
- No Warthog shadow
- Overbright dynamic lights

Here are some screenshots I took earlier with D9VK 0.22 (I'm currently having trouble producing fullscreen screenshots for some reason). The above issues appear identical to current build.
![D9VK 0 22-3](https://user-images.githubusercontent.com/1274826/69871116-09996200-1306-11ea-907a-bd8760cdccad.png)
![D9VK 0 22-5](https://user-images.githubusercontent.com/1274826/69871117-0bfbbc00-1306-11ea-99d0-7f9242e31034.png)

You may also note that the game is rendering incorrectly--it has the appearance of overscan, but the scaling is distorted. This is still occurring with the latest master build, with RX 580.

**Comment by gbMichelle** [comment]
No such over-scan issues on my setup.

Sadly no improvements since the last time I reported. It's pretty much in the same state as at the start of this thread except for the decals on the bases showing up now.

Tested with build from commit aa8d4979

**Comment by gbMichelle** [comment]
Christmas present!
🎄 🦊 🎁 
A working trace! https://drive.google.com/open?id=13Ia-2hXTrUtGSZ5AtBVTRb3CN53kikyM
It will look a bit different than the usual game because it is in a different rendering mode that doesn't make use of render targets. But it still shows off discrepancies between the two rendering pipelines. Importance for CE? It shows off one of the most noticable visual bugs that makes Damnation (The map in the trace) unplayable.
![2019-12-18-19-26-39-526-qapitrace](https://user-images.githubusercontent.com/24233409/71112761-83699080-21cc-11ea-96f7-e2e4b39d3a0c.png)
Left native, right d9vk

**Comment by gbMichelle** [comment]
Call 928428 is what renders the big white blobs for one of the frames. I notice that an effect that is rendered before this one is also over-saturated. If you don't mind speculation I suspect that some color values aren't being clamped entirely properly.
![Screenshot_20191219_091528](https://user-images.githubusercontent.com/24233409/71156375-2efff880-2240-11ea-9bd0-13c7eb00e613.png)
![Screenshot_20191219_091537](https://user-images.githubusercontent.com/24233409/71156376-30c9bc00-2240-11ea-9758-939e2dd93684.png)

**Comment by Joshua-Ashton** [comment]
Looks like dodgy specular to me

**Comment by gbMichelle** [comment]
This is awesome I just compiled doitsujin/dxvk commit 90ce37c.

The specular, the shadows, headlights, decals are all fixed. And it even performs amazingly now!

I will get you a trace of the shield effect next time I'm on Windows. That is, if it renders in that specific rendering mode.

**Comment by Joshua-Ashton** [comment]
Weird. But very happy for you. I have no idea what fixed that myself haha.

Lmk when you get some shield stuff and I'll look into it

**Comment by gbMichelle** [comment]
https://drive.google.com/open?id=1AC0ZOHh4DA3eCzYzUZG3bwbigOpm11Gb
Tested, shows the shield effect at full force. It's not super important. But I'm giving it so you can make D9VK as accurate as possible.
![shield](https://user-images.githubusercontent.com/24233409/71311865-7050fd80-2424-11ea-88ea-dce79597dca0.png)

**Comment by Joshua-Ashton** [comment]
Given that I won't be able to take a look today most likely, can you provide a comparison between native and D3D9 so I know what I am looking for when I do investigate?

Cheers.

**Comment by gbMichelle** [comment]
Native:
![shield](https://user-images.githubusercontent.com/24233409/71311910-fec57f00-2424-11ea-8d9c-6a143c7d73f6.png)
D9VK:
![haloce 12 trace_frame_185-1_1](https://user-images.githubusercontent.com/24233409/71311912-06852380-2425-11ea-804f-c54fd3bfa811.png)
Basically only half of the effect renders.

**Comment by gbMichelle** [comment]
It was something I did with how I compiled it. I have been running the game with dxvk through lutris. And I just put the build alongside with the other builds it has downloaded. Now what turns out is that most of these shader bugs only happen when you have the x64 folder present in your build. But not when it's not. Furthermore, the performance issues only happen on the x64 version.

How this ties into how I built it? I didn't want to wait for too long, so I turned off the building of the x64 libraries. Turned that back on when I decided to give a friend a build, and it was back.

I don't really know what to think of this tbh. I never thought the x64 libraries would even be used for the game. It's from 2001 and definitely 32-bit.

This is morphing into a different issue altogether...

**Comment by Joshua-Ashton** [comment]
Thanks that trace is great and straight to the point

**Comment by gbMichelle** [comment]
With this commit https://github.com/doitsujin/dxvk/commit/3ff9c4cc43aa8647a12fceb58dda580946c34df9
Only this issue remains:
https://github.com/Joshua-Ashton/d9vk/issues/427#issuecomment-567162612

**Comment by gbMichelle** [comment]
With commit https://github.com/doitsujin/dxvk/commit/d39ff9020eb04bf24448ff976663f783760861bb
The last problem in this issue has been fixed.
