### ISSUE TITLE
Mass Effect 2 messed up faces

### ISSUE THREAD

**Issue by AccountOneOff** [Joshua-Ashton/d9vk#54]
Everything seems to render fine except for Shepard's face and armor. Faces don't render right on some NPCs either. Also, menus don't align if the game resolution isn't equal to the screen res.

![canvas](https://user-images.githubusercontent.com/15083452/57004552-b51de080-6b84-11e9-832e-491a0257b2e6.png)

![canvas](https://user-images.githubusercontent.com/15083452/57004594-00d08a00-6b85-11e9-9e42-42c2575eff54.png)

https://www.youtube.com/watch?v=fsw_Onh66lE

### Software information
Mass Effect 2

### System information
- GPU: GTX 960
- Driver: 418.56
- Wine version: Wine Staging 3.21
- DXVK version: I don't remember

### Apitrace file(s)
- https://drive.google.com/open?id=1w25t1oM6on37bp_M5gtp29dtXQTFf0zh

### Log files
[ME2Game_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3133741/ME2Game_d3d9.log)

**Comment by ZachBacon** [comment]
I was gonna make a comment about how mass effect 2 always had messed up faces, but yeah that definitely is a rendering issue.

**Comment by neVERberleRfellerER** [comment]
This seems to be fixed now.
Tested with native d3dx9_{31,39,43}, d3dx10_39, d3dcompiler_39, d3dcompiler_43 (I get the list with `strings *.exe *.dll | grep -i '\.dll$' | sort -fu`)

**Comment by Joshua-Ashton** [comment]
Good to hear, can you get a picture to confirm this?

**Comment by neVERberleRfellerER** [comment]
![Screenshot_20190506_234726](https://user-images.githubusercontent.com/11160972/57257362-74790800-7059-11e9-8a70-fbb180019155.jpg)
I could take screenshot in the same area as OP did, but I'd prefer to keep my current autosave.

**Comment by AccountOneOff** [comment]
Please open back up this isn't fixed. This is with 7c1ba3ca

![Screenshot from 2019-05-07 16-09-40](https://user-images.githubusercontent.com/15083452/57338698-31fc0d80-70e3-11e9-8714-7151a1f0162f.png)

**Comment by Joshua-Ashton** [comment]
Yes, I think I know what broke it

**Comment by Joshua-Ashton** [comment]
Should be fixed by https://github.com/Joshua-Ashton/d9vk/commit/346120197aa74639e447e00978a2538dcb6d3635

**Comment by AccountOneOff** [comment]
That didn't fix it.

![Screenshot from 2019-05-07 16-48-25](https://user-images.githubusercontent.com/15083452/57339910-6920ed80-70e8-11e9-880f-4e61735a9f00.png)

[ME2Game_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3154907/ME2Game_d3d9.log)

**Comment by Joshua-Ashton** [comment]
Interesting...

**Comment by Joshua-Ashton** [comment]
Can you try on latest now? I fixed an alpha testing bug which may be related to her face decals rendering

**Comment by AccountOneOff** [comment]
From what I can tell it got a little better but it's still not right. Especially if you look at the suit.

https://streamable.com/fbm9s

**Comment by neVERberleRfellerER** [comment]
I don't have these problems.

**Comment by mitigd** [comment]
Reporting in to also say that I also have this issue with the latest version of D9VK & Nvidia Driver 430.09 & wine tkg-4.6. Could be a driver or card specific problem and doesn't seem to be isolated to one area either.

**Comment by AccountOneOff** [comment]
@neVERberleRfellerER [ME2Save.zip](https://github.com/Joshua-Ashton/d9vk/files/3159747/ME2Save.zip)

**Comment by neVERberleRfellerER** [comment]
Looks good to me under all randomly positioned angles and with both motion blur and without and with film grain and without (tested "just in case").
![Screenshot_20190510_122937](https://user-images.githubusercontent.com/11160972/57521306-35c8a380-7320-11e9-9d06-6e1790b4b39b.jpg)

**Comment by Joshua-Ashton** [comment]
Looks like its working with with radv but not nv then?

**Comment by neVERberleRfellerER** [comment]
Probably. It renders correctly for me even without any native d3dx* and d3dcompiler_*. I am on wine-tkg-git 4.7 now, but it worked just fine even with 4.6, which one reporter with nvidia uses too (https://github.com/Joshua-Ashton/d9vk/issues/54#issuecomment-490435788).

**Comment by dlshinobi** [comment]
Can confirm that with nVidia GTX 960 ver. 418.49.04 drivers and master d9vk (7ee2240) problem remains. ![me2_gliches](https://user-images.githubusercontent.com/7222444/57573053-5b8e9f00-742b-11e9-8e5f-dbecb483f110.png)

**Comment by neVERberleRfellerER** [comment]
AMDVLK v-2019.Q2.3 also renders this correctly
![Screenshot_20190513_133250](https://user-images.githubusercontent.com/11160972/57618474-cb17a200-7583-11e9-894a-bf177f953634.jpg)

**Comment by neVERberleRfellerER** [comment]
Big news. Look at the mirror:
![Screenshot_20190516_220333](https://user-images.githubusercontent.com/11160972/57883487-94ad8180-7826-11e9-8732-858e909afbc7.jpg)
It's the same with both AMDVLK and RADV git. It looks quite similar to broken rendering with nv, doesn't it?
It renders correctly with wined3d. Do you want apitrace of this?

**Comment by Joshua-Ashton** [comment]
Fixed by 6b12583491eaab7d2a3d7b1ff1fd5dc9392761f2

of which it took 3 times for me to commit correctly :frog:
