### ISSUE TITLE
Supreme Commander: Forged Alliance. Multiple Issues

### ISSUE THREAD

**Issue by pipnina** [Joshua-Ashton/d9vk#77]
Summary of issues that aren't present in unmodified proton:
1: Mouse cursor is invisible in-game
2: Game cannot be alt-tabbed out of (it loses focus, but stays on the screen, preventing any other program coming to front)
3: Shimmering effect where the visible sections of fog of war is supposed to be rendering
4: Commander does not animate (may relate to other units, but the building swarm for Cybran was animated)

Not sure how to get an apitrace from games run through proton natively in the steam client. Tried to run it the suggested way and it gave me 
`~/.steam/steam/steamapps/compatdata/9420/pfx/drive_c/apitrace-msvc/x86/bin$ WINEPREFIX="/home/james/.steam/steam/steamapps/compatdata/9420/pfx/" wine apitrace.exe trace -a dxgi /home/james/.steam/steam/steamapps/common/Supreme\ Commander\ Forged\ Alliance/bin/SupremeCommander.exe 
002d:err:vulkan:wine_vk_init Failed to load libvulkan.so.1.
002d:err:vulkan:wine_vk_init Failed to load Wine graphics driver supporting Vulkan.
002d:err:module:LdrInitializeThunk "winevulkan.dll" failed to initialize, aborting
002d:err:module:LdrInitializeThunk Initializing dlls for L"Z:\\home\\james\\.steam\\steam\\steamapps\\common\\Supreme Commander Forged Alliance\\bin\\SupremeCommander.exe" failed, status c0000142
warning: C:\apitrace-msvc\x86\bin\..\lib\wrappers\dxgitrace.dll was never used: application probably does not use this API
002a:fixme:kernelbase:AppPolicyGetProcessTerminationMethod 0xfffffffa, 0x32fe3c
0009:fixme:kernelbase:AppPolicyGetProcessTerminationMethod 0xfffffffa, 0x33fe3c
`

### Software information
Game was run at 2560x1440, on max settings, vsync disabled

### System information
- GPU: GTX 1070
- Driver: 418 (Ubuntu PPA)
- Wine version: Proton 3.16-9
- DXVK version: D9VK 0.10

### Apitrace file(s)
:(

### Log files
Can't find these in the game's install folder, do I need to use some kind of argument to get them to generate?
- d3d11.log:
- dxgi.log: 
![Supreme Commander BUGS SHOT 1](https://user-images.githubusercontent.com/6831528/57409336-f09d5800-71df-11e9-9cf4-aa29b0cfed67.png)
![Supreme Commander BUGS SHOT 2](https://user-images.githubusercontent.com/6831528/57409337-f09d5800-71df-11e9-8e50-6499e2db0afb.png)

Sorry I can't be fully helpful at first, but with some direction I can provide the rest of the info and re-test as necessary :D 
Thanks!

**Comment by NerosTie** [comment]
![20190825150200_1](https://user-images.githubusercontent.com/4572452/63650317-a36ed300-c749-11e9-9ff3-656237051b1c.jpg)

Some bugs are fixed. All the glitches are gone and the units are animated. The only thing I can see is the mouse cursor is flickering a lot (but without d9vk too! But less). Not sure if alt-tabbing is related to d9vk.

**Comment by pipnina** [comment]
@NerosTie It seems like the version of D9VK shipped by proton 4.11-2 does fix those previous issues! It even has working bloom and extra effects working!
For me the mouse cursor issue is not present on either the original DX9-OpenGL converter or D9VK. This is with an I7-6700k/GTX1070/430 nvidia driver.

Hopefully it fixes the old issue with the basic wine converter where the game crashes after a certain time.
@Joshua-Ashton Thanks :D

**Comment by pipnina** [comment]
I did a proper test just now. It's done way better than the basic wine DX implementation but sadly it does still crash eventually. Thankfully at 50 minutes on an 81km map instead of 10.

It gives a DXVK memory error at the bottom of my log file which could be investigated?
[steam-9420.log](https://github.com/Joshua-Ashton/d9vk/files/3538519/steam-9420.log)

**Comment by NerosTie** [comment]
Which version of d9vk?

**Comment by pipnina** [comment]
I'm using unmodified proton 4.11-2 which uses D9VK 0.13f

**Comment by NerosTie** [comment]
0.13f is very old now, you should download the latest version. You can download it here: https://git.froggi.es/joshua/d9vk/-/jobs/

**Comment by Joshua-Ashton** [comment]
Play with ``PROTON_FORCE_LARGE_ADDRESS_AWARE``
